### ISSUE TITLE
Paella: Problems with UI

### ISSUE THREAD

**Issue by oas777** [elan-ev/tobira#1196]
![grafik](https://github.com/elan-ev/tobira/assets/1752342/0b2a17a5-3615-45e9-90cb-bb59837fd6e6)

**Comment by owi92** [comment]
Yes, the slide previews need to have a higher resolution. And apparently the separating lines also 🤨

Apart from that, the issue title implies that there are other things wrong with the UI. I'm not saying there aren't but could you be more specific? I.e. maybe there are too many icons/buttons, or you dislike the lines in general or something else.

**Comment by oas777** [comment]
Thanks, Ole.
- Abandon vertical separation lines in the control bar. There are breaks to indicate slide changes already: 
![grafik](https://github.com/elan-ev/tobira/assets/1752342/22da1f65-2268-487b-9f9a-35e2e48d4fe2)
- All the icons in the two videos to switch, enlarge and delete one of the two videos create too much noise in there, together with the browser's icon to play this picture-in-picture. Mind you, the "move to next slide" icon is missing. Can we soften them altogether? Display some of them only in full screen mode? Or at least get rid of "enlarge"?
- The font for the resolution looks odd.

**Comment by LukasKalbertodt** [comment]
It looks like the screenshot was taken on a fairly small screen? On my 4k @ 200% (= 1080p) monitor, it looks like this:

![image](https://github.com/elan-ev/tobira/assets/7419664/fc5c2803-7621-495b-8f7f-7ea3614d824b)

That's a lot less crammed, obviously. Are you sure, you haven't accidentally zoomed in in your browser? But yes we had this topic once, and I think you have this one notebook where you have a fairly high UI scaling, resulting in a fairly low logical resolution.

---

Obviously, Tobira should still look fine on small screens! So this issue is valid no matter what. We should improve the situation.

> Abandon vertical separation lines in the control bar. There are breaks to indicate slide changes already:

I unfortunately don't understand. "There are breaks"? What breaks?

> All the icons in the two videos to switch, enlarge and delete one of the two videos create too much noise in there, together with the browser's icon to play this picture-in-picture. [...] Can we soften them altogether? 

I agree about the noise. I wonder if we can disable the browser's PiP button. What do you mean by "soften"? I could imagine making these buttons/icons smaller on smaller screens?

> Display some of them only in full screen mode? Or at least get rid of "enlarge"?

I don't think these are good ideas. The buttons give useful functionality that's not only useful in fullscreen. Also, "enlarge" is a function I use all the time, for example: have the slides as big as possible but still show a small talking head next to it.

> Mind you, the "move to next slide" icon is missing.

This would be on the bottom control bar, not "inside the videos", right?

> The font for the resolution looks odd.

How so?

---

Some additional points:
- The control bar and all the "in video overlay" buttons should disappear once you play the video. So the noise is only there when you have it paused or are moving your mouse inside the player. I think that makes the problem a lot less big.
- I could imagine hiding a few things from the control bar in a settings menu, like YouTube does. Like: playback speed and resolution.
- I would move the fullscreen button to the bottom righ... always. Everything else confuses users I am pretty sure.
- The fourth button from the right in the control bar (in your screenshot) is useless I think. It allows you to select what videos to show. But the "overlay buttons" for each video already allow you to do exactly that. I would remove that alltogether, or move it into the "settings" menu at the very least.

**Comment by oas777** [comment]
> It looks like the screenshot was taken on a fairly small screen? On my 4k @ 200% (= 1080p) monitor, it looks like this:
> That's a lot less crammed, obviously. Are you sure, you haven't accidentally zoomed in in your browser? But yes we had this topic
> once, and I think you have this one notebook where you have a fairly high UI scaling, resulting in a fairly low logical resolution.
Yes, my "small screen" (no zoom) certainly highlights the problem, but if I understand correctly, we agree we have to think about poor devils like me as well. By the way, most of the problems persist on the large screen I'm now looking at (plus, the preview images are fairly small).

> > Abandon vertical separation lines in the control bar. There are breaks to indicate slide changes already:
> I unfortunately don't understand. "There are breaks"? What breaks?
There are gaps (?) already to show the slide changes:
![grafik](https://github.com/elan-ev/tobira/assets/1752342/487ca6d2-37b4-43a7-843d-39ee8b0e85d7)
No need to mutilate this with vertical lines:
![grafik](https://github.com/elan-ev/tobira/assets/1752342/dce08a34-811e-4e2a-9e38-e2ae36aa3031)

> > All the icons in the two videos to switch, enlarge and delete one of the two videos create too much noise in there, together with the browser's icon to play this picture-in-picture. [...] Can we soften them altogether?
> I agree about the noise. I wonder if we can disable the browser's PiP button. What do you mean by "soften"? I could imagine making these buttons/icons smaller on smaller screens?
I just looked at Chrome and PiP seems to be a Firefox "feature" - would be great if you were able to get rid of that. "Soften" means to make them less obvious or "in your face", not so much by making them smaller but maybe by making them more transparent? 

> > Display some of them only in full screen mode? Or at least get rid of "enlarge"?
> I don't think these are good ideas. The buttons give useful functionality that's not only useful in fullscreen. Also, "enlarge" is a function I use all the time, for example: have the slides as big as possible but still show a small talking head next to it.
Well, if we keep all the features, we certainly have a task ahead to make the total appearance less "crammed".

> > Mind you, the "move to next slide" icon is missing.
> This would be on the bottom control bar, not "inside the videos", right?
"Why not?" asked the developer:
![grafik](https://github.com/elan-ev/tobira/assets/1752342/45a1cd0f-73a6-4097-a9f8-ec592eddbe5e)

> > The font for the resolution looks odd.
> How so?
Looks better with the larger screen, but still ... maybe because it's black on white in contrast to the other figures? Anyway, let's forget about this one.
 
> Some additional points:
> 
>     * The control bar and all the "in video overlay" buttons should disappear once you play the video. So the noise is only there when you have it paused or are moving your mouse inside the player. I think that makes the problem a lot less big.
Yes, hiding problems makes them smaller. But doesn't solve them. 

>     * I could imagine hiding a few things from the control bar in a settings menu, like YouTube does. Like: playback speed and resolution.
Is that you dreaming of having control over PP?

>     * I would move the fullscreen button to the bottom righ... always. Everything else confuses users I am pretty sure.
+1
 
>     * The fourth button from the right in the control bar (in your screenshot) is useless I think. It allows you to select what videos to show. But the "overlay buttons" for each video already allow you to do exactly that. I would remove that alltogether, or move it into the "settings" menu at the very least.
The other way round: Isn't that the "settings" menu which would allow to remove some of the icons in the video area?

**Comment by oas777** [comment]
PS: Not very well formatted, apologies.

**Comment by oas777** [comment]
> Oh and: I find it very ugly that the preview image for a section is either left or right of the cursor, instead of centered (if possible). That needs to be fixed in Paella tho.

+1

**Comment by oas777** [comment]
Stumbling upon the resolution font again:

![grafik](https://github.com/elan-ev/tobira/assets/1752342/7351e61a-2bc7-4c48-98b6-b6aad12b50c5)

The alignment and the font (regular/bold) combined give you the impression we have four different styles for four different sets of figures (time, +/- 10s, speed, resolution).

**Comment by dagraf** [comment]
I have no strong opinions here. Mainly because I find the discussed issues not that UI issues not that pressing and we have quite a lot of missing features/functionalities I would like to focus our attention up on.

Having said that, some remarks:
- I would also move the fullscreen button to the bottom right.
- Hitting on the "Video-layout" button and then scrolling down leads to the options being moved down while scrolling. I would expect the options to stay over the video.
<img width="973" alt="Bildschirmfoto 2024-07-09 um 22 40 50" src="https://github.com/elan-ev/tobira/assets/15246287/d9d152ab-bb04-4371-82da-afea9f307613">
