### ISSUE TITLE
Search result list on mobile: Search results are indistinguishable if no result is chosen

### ISSUE THREAD

**Issue by oas777** [elan-ev/tobira#1275]
If you scroll through search results on mobile, the search result highlighted (where you started scrolling) disappears and results are shown without the highlighting effect to separate them. Could we change that by "forcing" the highlighting? Or have other separators?

![image](https://github.com/user-attachments/assets/65cccd4c-6f42-48a8-8769-c48d2f54cdf0)

**Comment by LukasKalbertodt** [comment]
Oh wow, I completely missed this issue, sorry. Since the new search design is still not merged, my assumption is, that everything related to that is commented on the PR directly. 

Now I understand what you mean. With the new increased distance in my latest changes, I think the separation is not a problem anymore, personally.

**Comment by oas777** [comment]
Well, they are now "distinguishable", but the highlighting still could be nice ...
