### ISSUE TITLE
Database migration with data

### ISSUE THREAD

**Issue by lkiesow** [elan-ev/tobira#130]
Right now database migrations will fail if the database holds any data. This is something we need to fix for the first release.
Right now, the best we can do is to reset the database by running:

```sh
tobira db reset
tobira db script scripts/fixtures.sql
```

**Comment by LukasKalbertodt** [comment]
I think this needs a bit more explanation, because "database migrations will fail if the database holds any data" isn't exactly true. 

The Tobira application knows about a list of migrations. The database also stores a list of migrations that were applied to it (including ID, the date when it was applied and the actual migration SQL script). Tobira will compare these two lists by comparing the IDs of the migrations *and* the actual migration SQL script.

- If both lists are the same: great, nothing to do, DB up to date.
- If the list in the database is a subset of the list the Tobira application knows about: apply the missing migrations to the database.
- If the database holds more migrations than Tobira knows about, it exits with an error.
- If, however, the SQL script of the migration with a specific ID differs between the database and the tobira application, then Tobira will exit with an error. Because: what else is it supposed to do?

Tobira could be a little bit smarter if we had `down.sql` scripts (reverting one migration script), but that also doesn't solve the fundamental problem. That we at least have to undo one migration of the script differs.

However, this is not as bad as it sounds! This error happens only if (a) we change existing migration scripts, or (b) we switch between two branches that both add a new migration. The last point is irrelevant for production users. And regarding (a): we can just not change existing migration scripts but rather add new scripts which change existing tables. 

Currently, the "reset DB and run all migrations again" is common because we were in a sprint week were multiple DB-changing PRs were in flight at the same time. And because we are still early in development, we change existing migration scripts a lot because it results in fewer scripts and right now, we don't have any data we need to preserve. But once we release a public Tobira version we must make sure that we never change any migration scripts that were released with it. Otherwise yes, that would be bad. (Maybe we want some automated check for that, actually, ... mh.)

I hope this explains the situation a bit better.
