### ISSUE TITLE
Add automatic login for Studio and Editor

### ISSUE THREAD

**Issue by LukasKalbertodt** [elan-ev/tobira#363]
The integration of Opencast Studio and the new video editor is currently super simple: it's just a link. And this works okay if the user can also log into Opencast. But this is not always a given (and avoiding a login mask would be useful regardless). We somehow want to improve this.

One option would be to create a user session in Opencast that is stored in the users browser. The Tobira frontend would get a JWT from the backend, send it to some API endpoint in Opencast, which then replies with a `Set-Cookie` header that the user's browser can store. As far as we know, there is no such route in OC yet where we can trade a JWT for a login session. Also, it's not clear whether this 3rd party cookie stuff works in modern browsers. 

An alternative would be to have a special endpoint in OC that takes a JWT and a redirect URL as query parameters. Then we only need to link to it and can avoid any 3rd party cookie madness.

Finally, Tobira couuuuld somehow proxy the editor/studio by including it in some iframe or *something*. Then it might be able to intercept and edit all outgoing requests to Opencast to add a JWT to it.

**Comment by JulianKniephoff** [comment]
Some random thoughts from an initial brainstorming about this:

* The last option has the appeal that we can implement it by touching Tobira only, but it has two major drawbacks:
  * The URL of the Tobira page that "wraps"  Editor/Studio somehow **has** to be different from where these tools are normally served, because we need a place to put the `iframe` and the Service Worker. So then there are two URLs for Studio/Editor. That's confusing. Or you hide the "normal" URL and only expose them through the Tobira URL, but that could be confusing as well. **Or** you do magic tricks in your reverse proxy and let Tobira handle the "normal" Studio/Editor-URL, but then it's not a Tobira-only solution anymore, but even depends on particularities of the deployment.
  * The Service Worker would have to manage the JWTs expiring which sounds like a bit of a nightmare. Or we use super long-lived JWTs which is of course not recommended.
