### ISSUE TITLE
Language selection in the primary menu

### ISSUE THREAD

**Issue by mdorferf** [elan-ev/tobira#448]
Hi,
thank you for the work you put into Tobira! 

We noticed that the language selection was difficult to find. Perhaps this could be made a little more visible by putting it in the primary menu. 

Thank you for your help in advance and keep up the great work!

Best regards
Maria Dorfer-Frick (TU Wien)

**Comment by LukasKalbertodt** [comment]
Mh, are you suggesting that the language icon should be visible in the header, without a click? I.e. next to the login button/the "logged in as" thing? So that changing the language only requires two clicks (on language icon, then on the language) instead of the three it requires now? Is that what you're suggesting?

**Comment by mdorferf** [comment]
Hi,
thank you for the summary! That's exactly what we were considering, as it would make the language setting more visible. 
Best regards
Maria Dorfer-Frick
