### ISSUE TITLE
Tobira only works with "public" schema

### ISSUE THREAD

**Issue by ziegenberg** [elan-ev/tobira#635]
Tobira has the `public` schema hard coded (eg. https://github.com/elan-ev/tobira/blob/master/backend/src/db/query.rs) and does not work with other schemas.

**Comment by ziegenberg** [comment]
If you set `search_path = "$user"` for the database user, Tobira automatically uses the schema named after its database username. This works for all queries where the schema is not explicitly mentioned in the query.

**Comment by ziegenberg** [comment]
Yes, we use the schema `tobira` in our deployment as we do not trust the users in the `public` schema. In the public schema "EVERYBODY" can write, using the default PostgreSQL settings.

For details see: https://www.postgresql.org/docs/current/ddl-schemas.html

**Comment by ziegenberg** [comment]
It would need changes in the following two functions:
https://github.com/elan-ev/tobira/blob/9aff8d7c0509e030c87bc7d4c48d79bc4ced2895/backend/src/db/query.rs#L6-L17

```diff
            "select table_name from information_schema.tables \
-                where table_schema = 'public' and table_type = 'BASE TABLE'",
+                where table_type = 'BASE TABLE'",
```

https://github.com/elan-ev/tobira/blob/9aff8d7c0509e030c87bc7d4c48d79bc4ced2895/backend/src/db/query.rs#L19-L30

```diff
        "select exists(
            select * from information_schema.tables
-                where table_schema='public' and table_name=$1
+                where table_name=$1
        )",
```

**Comment by LukasKalbertodt** [comment]
I finally managed to read up on schemas in PostgreSQL.

If I understand everything correctly, simply removing the `where schema = 'public'` condition is actually incorrect. Because then we would also list tables from other schemas that the user has access to. I think replacing `'public'` with `current_schema()` is a better solution. I would do the following changes:

- Document that `current_schema()` must always refer to the same schema over the lifetime of a Tobira installation. I think this is a reasonable requirement. All objects created and used by Tobira should be stored in one schema.
- Replace all occurrences of `'public'` with `current_schema()`. I am aware that `current_schema` is just the first schema in the search path which exists. But this is also exactly the schema where new objects are created. So I think it should all work out well.
- Change the `clear` function to not drop the schema, but instead only drop all objects inside it. It is more work but it's the better solution IMO. For example, already saw installations where the user actually wasn't allowed to drop the schema. 

This would also imply closing the PR by @geichelberger. 

What do you think about this plan? Is my understanding of the situation correct?
