### ISSUE TITLE
Share functionality on video page: Make different options easier to understand

### ISSUE THREAD

**Issue by dagraf** [elan-ev/tobira#743]
At the moment, under the button "Share video" there are three different options available to share a video. The two options that generate a link offer different links. Tobira should explain this difference better. See mockup for suggestions.

[Video teilen optimieren_20230315.pdf](https://github.com/elan-ev/tobira/files/10982094/Video.teilen.optimieren_20230315.pdf)

**Comment by oas777** [comment]
David, the new implementation of "Share" can be found at https://tinyurl.com/2emkhb2s. Some comments:

- Einbetten: Does a QR code make sense to embed?
- Einbetten: Firefox prevents embedding, cf. https://nurfuerfritz.blogspot.com/2023/01/tobira-1.html, so does Chrome. Safari doesn't show anything.
- Direktlink: How about we rename it "Videolink"?
- Direktlink: How about "Hiermit wird das Video direkt verlinkt, nicht die Seite des Videoportals. Der Link funktioniert auch, wenn die Seite gelöscht oder verschoben wird."?

**Comment by LukasKalbertodt** [comment]
Just answering part of your comment for now:

> Firefox prevents embedding, cf. https://nurfuerfritz.blogspot.com/2023/01/tobira-1.html, so does Chrome. Safari doesn't show anything.

This is just the Tobira test deployment, not Tobira in general. In technical terms: it depends on how you configure your webserver, and specifically if you set the `X-Frame-Options` header. 

> Does a QR code make sense to embed?

QR codes can contain arbitrary data. And if a user wants to edit some blog on phone and needs the embed code there, it could be useful. I don't expect this to happen a lot, but it's no work for us to have this button there and it makes the design more consistent.

**Comment by oas777** [comment]
Fine. So let' talk about the "Direktlink" once you had the time to discuss this.

**Comment by dagraf** [comment]
My thoughts to the new implementation:

- Einbetten: I think there is not much use of a QR-Code for embedding. Therefore, I would not offer it. But I do not have a strong opinion here. We can also leave it there for consistency reasons.
- Direktlink: I would prefer the name "Videolink".
- Direktlink: I like the explanation of @oas777, but would suggest a shorter version (which is consistent with the suggested wording for 'Seitenlink', see below): "Link zum Video, nicht zur Seite des Videoportals. Der Link funktioniert auch, wenn die Seite gelöscht oder verschoben wird."
- Seitenlink: I think we need an explanation similar to the one for Direktlink. How about "Link zur Seite im Videoportal. Der Link funktioniert nicht mehr, wenn die Seite gelöscht oder verschoben wird."?
- What do we offer under "Teilen", when a user is under "My videos" and hits on "Teilen". Does the "Seitenlink" makes sense here? I do not think so. Should we either not offer it or do we need to alter the explanation to "Link zur **aktuellen** Seite im Videoportal. Der Link funktioniert nicht mehr, wenn die Seite gelöscht oder verschoben wird."? And for the Direktlink: "Link zum Video, nicht zur **aktuellen** Seite des Videoportals. Der Link funktioniert auch, wenn die **aktuelle** Seite gelöscht oder verschoben wird."

**Comment by LukasKalbertodt** [comment]
Regarding the whole direct link and page link discussion: in yesterday's meeting we had another idea how we can get away with just showing the "page link". After a bit more thought, we (devs) think that its a good way forward to avoid confusion. Because no matter how good and brief our explanation text is, there would always be users confused by it and the process of sharing a video will always seem more complicated to users. 

To explain the idea, here a quick recap:
- Each video has an ID like `PfGpl8VuH6q`.
- When I say "navigation" in the following, I am referring to the breadcrumbs and also to the main navigation element (the left box on desktop, the burger menu on mobile).
- Video direct links look like this: `/!v/<id>`, e.g. `/!v/PfGpl8VuH6q`. These have no "page context" and thus, the navigation of the start page is shown.
- Then there are "video in page context" links which look like this: `/path/to/page/v/<id>`, e.g. `/lectures/d-baug/2007/spring/101-0012-00L/v/PfGpl8VuH6q`. Here, we show the navigation of the page.

So far, the "video in page context" link will check whether a page with the given path exists. If it does not, Tobira will show 404 not found. (Regardless of whether a video with that ID exists!). The idea is: If a "video in page context" link is opened and the page does not exist, but the video exists, Tobira would redirect the user to the direct link automatically, i.e. to `/!v/<id>`. That means that a "video in page context" link is strictly more powerful/versatile than a direct link. If the page exists, the corresponding navigation is shown. If the page got removed, no worries, it falls back to just being a video direct link. There is thus no need for the user to chose between the two different links, as one is always better than the other. Thus, we would not show a "direct link" option or explanations in the share menu. 

Mind you, direct links will still continue to work. And in particular, if a video is not included in any page yet, a user with write access can share a direct link from within "my videos". So the use case "just upload, don't put it on a page, and share" is still covered.

I think this is a better option than any specific explanation we could come up with.
Our plan was to just implement that and then talk about it again at our next meeting. Unless you already want to veto that now.

**Comment by LukasKalbertodt** [comment]
> Where can we place the options we want to have in the future (for example "Start at x:xx" or "Don't show title")? I would suggest between the Link an the button for "QR Code zeigen".

Yes, that was exactly the plan. This was my sketch for this new share menu design:

![image](https://user-images.githubusercontent.com/7419664/235927045-d7529d19-d0dc-4a6d-97f7-60ff7bda00c9.png)

New kinds of "share things" can be new tabs (like RSS in my sketch). The "start at timestamp" goes below the link as you suggested. What I don't understand is your "don't show title": what do you mean by that?

To avoid further confusion in my sketch: The button on the bottom right there is a potential "native share" button we might add in the future. This would open the share menu provided by your operating system. This, as far as I know, is currently only available on mobile.

**Comment by dagraf** [comment]
> Regarding the whole direct link and page link discussion: in yesterday's meeting we had another idea how we can get away with just showing the "page link". After a bit more thought, we (devs) think that its a good way forward to avoid confusion. Because no matter how good and brief our explanation text is, there would always be users confused by it and the process of sharing a video will always seem more complicated to users.
> 
> To explain the idea, here a quick recap:
> 
>     * Each video has an ID like `PfGpl8VuH6q`.
> 
>     * When I say "navigation" in the following, I am referring to the breadcrumbs and also to the main navigation element (the left box on desktop, the burger menu on mobile).
> 
>     * Video direct links look like this: `/!v/<id>`, e.g. `/!v/PfGpl8VuH6q`. These have no "page context" and thus, the navigation of the start page is shown.
> 
>     * Then there are "video in page context" links which look like this: `/path/to/page/v/<id>`, e.g. `/lectures/d-baug/2007/spring/101-0012-00L/v/PfGpl8VuH6q`. Here, we show the navigation of the page.
> 
> 
> So far, the "video in page context" link will check whether a page with the given path exists. If it does not, Tobira will show 404 not found. (Regardless of whether a video with that ID exists!). The idea is: If a "video in page context" link is opened and the page does not exist, but the video exists, Tobira would redirect the user to the direct link automatically, i.e. to `/!v/<id>`. That means that a "video in page context" link is strictly more powerful/versatile than a direct link. If the page exists, the corresponding navigation is shown. If the page got removed, no worries, it falls back to just being a video direct link. There is thus no need for the user to chose between the two different links, as one is always better than the other. Thus, we would not show a "direct link" option or explanations in the share menu.
> 
> Mind you, direct links will still continue to work. And in particular, if a video is not included in any page yet, a user with write access can share a direct link from within "my videos". So the use case "just upload, don't put it on a page, and share" is still covered.
> 
> I think this is a better option than any specific explanation we could come up with. Our plan was to just implement that and then talk about it again at our next meeting. Unless you already want to veto that now.

Thanks for summarising your discussion: Making sharing as easy and intuitive as possible is the way to go, I agree. What we should consider in my opinion and maybe best discuss in our next meeting: When users or admins delete a page in Tobira or unmount a series in an existing page in Tobira what expectation do they have considering the links they have shared to the videos of this series? I assume that they assume that these links too stop working. But maybe I'm wrong. Let's discuss this in our next meeting.

**Comment by dagraf** [comment]
> What I don't understand is your "don't show title": what do you mean by that?

That is referring to a feature we do not have in Opencast yet (but may come later): The title of a video could be shown as an overlay over the thumbnail/video. [Example](https://www.unibe.ch/studium/studienangebote/kompetenzen_fuer_die_digitale_zukunft/ethik/index_ger.html)

**Comment by oas777** [comment]
PS: Ole, Lukas, please let us know whether this interaction (even if this one was a bit more complex) is helpful in executing tasks at hand. Instead of waiting for the next meeting...

**Comment by dagraf** [comment]
> * David, could you take "don't show title" to a new ticket please?

No, I will not. I have only mentioned it as a possible option. I do not see any need for this feature for now.

**Comment by dagraf** [comment]
> The idea is: If a "video in page context" link is opened and the page does not exist, but the video exists, Tobira would redirect the user to the direct link automatically, i.e. to `/!v/<id>`. That means that a "video in page context" link is strictly more powerful/versatile than a direct link. If the page exists, the corresponding navigation is shown. If the page got removed, no worries, it falls back to just being a video direct link.

I'm still quite skeptical that this (a link to a "video in page context" falls back to the direct link, when a page no longer exists) is a good idea. Because, if I get it right, with the now implemented solution I have to delete or unpublish a video I had once inserted on a page and shared via link in order to prevent people from being able to access this video. It is not enough to take it away from this page or to delete the page.

In fact, I picture a lot of users expecting the following:
- I have shared a link to a video in a page context.
- I delete this page or remove the shared video from this page (for example because it is outdated) because people should not be able to see it anymore (for example because it is outdated).
- Then people following the link I shared should NOT be able to see the video anymore.

**Comment by LukasKalbertodt** [comment]
I agree that users could have this assumption and that we should make it clear to users how things work. 

It is worth pointing out that even without PR #818, users who read the URL could already visit the direct link. Again, since the long link `/path/to/page/v/<videoid>` contains the video id, users can just manually assemble the direct link `/!v/<videoid>`. This was always possible. The new PR only makes it that Tobira performs this redirect for you. 
It's technically infeasible right now to completely hide the video ID from technically versed users for the "video in page context" link. Thus, getting the direct link is basically always possible.

I think we should teach the users (with good and clever UI) what deleting a page (or removing a video from a page) does. And what it doesn't. I think we should drive home one thing: if you don't want others to be able to view your video, change the ACLs to disallow that (we won't call it "ACLs" in the UI of course, sth like "access rights"). The ACLs are the proper solution for that. Everything else is brittle and does not protect anything, once the video was public once. *Controlling access* to a video should be done via *access control lists*, that's their point. 

And again, I absolutely agree with you that the UX should be good here and we should not risk users misinterpreting the situation, assuming something is private.

**Comment by LukasKalbertodt** [comment]
Can this issue be closed? The new share menu is now merged and can be seen on tobira.opencast.org. I everything mentioned here should be resolved? I just quickly skimmed this issue again and couldn't find any unresolved questions. If I missed something, let me know. Otherwise I will close this issue soon.

**Comment by oas777** [comment]
Cf. my comment https://github.com/elan-ev/tobira/issues/802: Either assign such tasks to David and myself (with information where to test them) or mark them differently so that we can check ex post (i. e. after a release). Simply closing tickets pushes them out of (my) sight.

**Comment by oas777** [comment]
Closed in favor of https://github.com/elan-ev/tobira/issues/806.
