### ISSUE TITLE
Fix player for portrait videos

### ISSUE THREAD

**Issue by LukasKalbertodt** [elan-ev/tobira#775]
Currently, non-16:9 videos do not use all the player container space. This looks especially ridiculous in the case of portrait videos. Take a look at this example: https://tobira.opencast.org/v/JZ2aKAZKlsw
EDIT: this is fixed for desktop screens. Try it with a narrow screen (e.g. smartphone)

As you can see, the outer player div has a good size (and one with the same aspect ratio as the video), but the actual video is tiny. 

I am not sure if this is Paella's fault or if our integration is just bad.

**Comment by owi92** [comment]
I have spent some time reading paella docs and code and trying to figure out the issue but I couldn't get to the bottom of this.

Paella definitely appears to support portrait style layouts and has a function to detect whether or not to apply it (by checking if video has width > height, see https://github.com/polimediaupv/paella-core/blob/02d7c733adb8d63d6aa7e2f449476a9bfb3222e7/src/js/core/VideoContainer.js#L152).
There are two types video layout (`static` and `dynamic`) and for portrait videos to work we would need it to be `dynamic` (https://github.com/polimediaupv/paella-core/blob/main/doc/video_layout.md#types-of-video-layout). I guess we have it set to `static`, but I can't really tell if that is really the case or even how to find out.

I think additionally we also need to look at how we provide the `previewImage` for portrait videos. There is a `portraitPreview` prop (https://github.com/polimediaupv/paella-core/blob/main/doc/video_manifest.md#metadata), which I tried with the thumnail (-> doesn't work because that always seems to be `1280 x 720`, even for portrait videos).
But I also tried this with a random [picsum](https://picsum.photos/) image where I set the width and height according to the video's aspect ratio (-> works). With that it isn't even required to use the `portraitPreview`, i.e. it also works when using this as the regular `previewImage`.

So yeah, overall I don't really have a clue about how we can fix this without overwriting the specific paella css classes.
You can see my workaround [here](https://github.com/elan-ev/tobira/compare/master...owi92:tobira:fix-portrait-experimental) (I know this isn't the right way to do it). I also played around with our paella configuration, but since that lead nowhere I didn't include those trials.

**Comment by LukasKalbertodt** [comment]
I poked around as well but couldn't find a solution. I think the video layout itself defines whether it's static or dynamic. And the `singleVideoLayout` we are using is static. Not sure if a dynamic one would fix it. But it also seems like all layouts are based on a 1280:720 base rect. The one that you overrode the height and width of in your workaround (`.base-video-rect`). 

The fact that our preview image is 16:9 with letterboxing is another issue, which I would ignore for now.

**Comment by oas777** [comment]
Do you want me to ask Miguel from Valencia to have a look?

**Comment by LukasKalbertodt** [comment]
> Do you want me to ask Miguel from Valencia to have a look?

Actually, yes. I already put it on our agenda for next meeting, but I can already tell you here: it would be really great if we could get assistance for a few Paella issues from the people from Valencia. This issue, #794 and potentially also #816 (though there I agree, ideally we would just switch to the good design ASAP). If you could contact them and ask them to look at the issues or talk to us via mail or video call or whatever, that'd be great!

**Comment by oas777** [comment]
Do we want him to take a look with the Paella version currently implemented? Or wait for us (you) to implement Paealla 7/ethz? I suppose some issues will be different in the latest version.

**Comment by miesgre** [comment]
Paella 6 defined a 16/9 canvas of 1280x720 and each layout decided how the videos were positioned on the canvas with static positions.

Paella 7 inherited this, but added the possibility to make dynamic layouts. Currently only for dual videos (`es.upv.paella.dualVideoDynamic`). For a single video the `es.upv.paella.singleVideo` layout is used, which still uses static layouts.
https://github.com/polimediaupv/paella-core/blob/b122209a50833c5487794cca2bbfcb840372b3bb/src/js/layouts/es.upv.paella.singleVideo.js#L62-L77

In theory it would be possible to transform this layout to a dynamic one and it should work.

Please, feel free to open an issue in [paella repository](https://github.com/polimediaupv/paella-core).

**Comment by miesgre** [comment]
@LukasKalbertodt Paella now supports portrait videos.
https://github.com/polimediaupv/paella-core/commit/bfe3bd421f017e65d330c321ba9453f057324bfb

Update to `paella-core@1.37.1`. You should change your `config.json` file. Change the `es.upv.paella.singleVideo` layout by `es.upv.paella.singleVideoDynamic`.

Tests:
- https://paellaplayer.upv.es/player.html?id=portrait
- https://paellaplayer.upv.es/player.html?id=portrait-dual

Documentation:
- https://paellaplayer.upv.es/#/doc/paella_core_plugins.md

**Comment by LukasKalbertodt** [comment]
@miesgre Thank you for the prompt update and release! Ole did what you said in #867 and we noticed that there is still some padding in the video container. [Example video](https://pr867.tobira.opencast.org/v/L5CUekz9uQ0). As you can see, there is still a small grey border all around the video. I don't think it has to do with our integration: in your test video links, there is the same grey border/padding. Could you look into that?
