### ISSUE TITLE
Live-Streams do not work on iOS devices

### ISSUE THREAD

**Issue by dagraf** [elan-ev/tobira#794]
Live-Streams delivered via Tobira do NOT work on iPhones (see screenshot). They do work on iPad (iOS 16.2). Tested with:

- tobira.opencast.org and on our own tobira installation 
- iPhone: iOS 16.2, iOS 16.4.1
- Browser: Safari, Chrome

Shown error message: "undefined is not an object (evaluating"

![MicrosoftTeams-image (13)](https://user-images.githubusercontent.com/15246287/234205138-9e67f237-9896-468a-aeac-876f8a8ad6fb.png)

**Comment by dagraf** [comment]
Not I, but we can. I get back as soon as we were able to test Paella 6 and 7.

**Comment by snoesberger** [comment]
I did a test with a live stream on our Opencast installation with the URL described by Lukas `/paella7/ui/watch.html?id=` and got a different error message: `Invalid video manifest: the 'metadata.preview' field is required.`
Using the Paella 7 player to play a recorded video worked fine. But I'm not sure if everything is configured correctly for Paella 7. We use Paella 6 for production.

**Comment by LukasKalbertodt** [comment]
So I researched a bunch and: Paella should support HLS live streaming on iPhones, as far as I can see from the docs and the code. Usually, `hls.js` is used (which requires the "media source extensions" feature from the browser, which Safari on iPhone does not support). But in Safari, HLS livestreaming is supported natively (at least some HLS streams). So in those cases, Paella should switch to native HLS streaming and everything should work. ([Relevant Paella code](https://github.com/polimediaupv/paella-core/blob/bcf1ebbda157be002daab29a135cf35afdd9bc75/src/js/videoFormats/es.upv.paella.hlsVideoFormat.js#L66-L86)).

But yeah, something is wrong. The error that happens on iPhones is:

> Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 'this._sources.sort')

The code `this._sources.sort` only exists in the MP4 video plugin. But why is that chosen? In [our Paella configuration](https://github.com/elan-ev/tobira/blob/24a33dc60034558c40ba00acad51c387f468f36b/frontend/src/ui/player/Paella.tsx#L206-L230), we set `order: 0` in the HLS plugins and `order: 1` on the MP4 plugin. So it should try HLS first. But apparently it then thinks that HLS is not supported or something?

I don't really know how to proceed, especially since debugging this is super hard (I do have an iPhone, but no Mac, so I can only use browser stack).
Excuse the random ping, but @ferserc1 do you have any hints as how to proceed? Is there something wrong with our configuration? Is it correct that Paella supports HLS live streaming on iPhones?

**Comment by LukasKalbertodt** [comment]
Actually, I cannot reproduce this anymore. Trying [this](https://tobira.opencast.org/live/v/OiUZv3adE8k) on iPhone works. I'm not entirely sure how I failed to properly test that before, but I think it might have to do with me trying only the German TV livestream (which is restricted to DACH IPs) from a device with a US IP. 

So if it still fails for you, please let me know so that I can try your exact video on your installation to debug the problem. Also: your installation has an older Tobira and thus also Paella version. Not sure if that's relevant.

**Comment by snoesberger** [comment]
We have now our test environment on Opencast 13 and Tobira 2.0 and I am able to correctly play HLS live streams on the Mac Xcode iPhone 14 simulator. With the same simulator, OC 12 and Tobira 1.7 I was not able to play such HLS live streams.

**Comment by LukasKalbertodt** [comment]
Ah, that's good to hear! So then this issue can be closed I suppose. If I'm mistaken, feel free to reopen!
