### ISSUE TITLE
Make the "Managment Dashboard" coherent

### ISSUE THREAD

**Issue by oas777** [elan-ev/tobira#808]
![image](https://user-images.githubusercontent.com/1752342/236029055-5e7dc275-cce2-443a-b989-25f59a305db4.png)

- Two submenus to the left , five in the middle, four to the right.
- "Dashboard" to the left, "Management Dashboard" in the middle, "Manage" to the right
- No hierarchy to the left, "Management Dashboard" under "Management" in the middle, submenus under "Manage" to the right

My suggestion would be to call it "Dashboard" with four submenus, "Log out" only to the right.

**Comment by LukasKalbertodt** [comment]
The "manage pages?" item should definitely be something else, i.e. just a normal text below.

The problem with "record video" (Opencast Studio) is that it opens a new tab with studio. We can't really make that a navigation item on the left as it would be very confusing to users, who expect a consistent behavior from these navigation items. But yeah, it's true that this is not optimal right now. We will try figuring something out!

**Comment by dagraf** [comment]
I'd like to add some suggestions:
- To improve clarity and consistency (example: we have "Your page" but "My videos"): Change wording for "Persönliche Seite"/"Your page" to "Meine Seite"/"My page". 
- Change icon for "Persönliche Seite"/"Your page" (Is this a flame?). See mockup.
- Don't show the navigation item on the left. This would be the most straight forward option to not confuse users. And users who are aware of the breadcrumb can still use this option to navigate back to the dashboard
- Use the same order for the options (in the middle and to the right). My Suggestion: "Meine Videos / Video hochladen / Video aufnehmen / Meine Seite" (but here I have no strong opinion)
- Improve consistency: Momentarily we have "Verwalten" (to the right), "Dashboard" (as title of the page) and "Verwaltung" (as breadcrumb). My suggestion: Rename "Dashboard"/"Management Dashboard" to "Inhalte verwalten"/"Manage content".
- Invest some time in rewriting some explanations for the 4 options. For example: Also start the explanation for "Meine Seite" with "Hier können Sie eine eigene Seite erstellen, auf der Sie frei ..."

<img width="1437" alt="Bildschirmfoto 2023-05-10 um 18 48 31" src="https://github.com/elan-ev/tobira/assets/15246287/c61874dc-eba6-474f-ae66-f99b5acd6705">

**Comment by oas777** [comment]
>To improve clarity and consistency (example: we have "Your page" but "My videos"): Change wording for "Persönliche Seite"/"Your page" to "Meine Seite"/"My page"

If it's "My videos", it should be "My pages" (plural). Or "My page(s)". Same in German.

>Change icon for "Persönliche Seite"/"Your page" (Is this a flame?). See mockup.
+1 for the mockup. But different order (s. below)

>Don't show the navigation item on the left. This would be the most straight forward option to not confuse users. And users who are aware of the breadcrumb can still use this option to navigate back to the dashboard
+1

>Use the same order for the options (in the middle and to the right). My Suggestion: "Meine Videos / Video hochladen / Video aufnehmen / Meine Seite" (but here I have no strong opinion)
+1

>Improve consistency: Momentarily we have "Verwalten" (to the right), "Dashboard" (as title of the page) and "Verwaltung" (as breadcrumb). My suggestion: Rename "Dashboard"/"Management Dashboard" to "Inhalte verwalten"/"Manage content".
That's a "no" from me. You can also upload content, that's not "Manage content" (nor is recording a video). Make it "Dashboard". 

>Invest some time in rewriting some explanations for the 4 options. For example: Also start the explanation for "Meine Seite" with "Hier können Sie eine eigene Seite erstellen, auf der Sie frei ..."

Are 4 minutes "some time"?
- Hier können Sie Videos von Ihrem Computer hochladen.
- Produzieren Sie Videos, indem Sie Ihren Bildschirm, Ihre Webcam und ihr Mikrofonsignal aufnehmen
- Hier finden Sie Ihre Videos und können diese verwalten und bearbeiten.
- Auf Ihren persönlichen Webseiten können Sie Videos, Text und andere Element kombinieren.

**Comment by dagraf** [comment]
Thumbs up for @oas777 comment above (https://github.com/elan-ev/tobira/issues/808#issuecomment-1542783966). 

I have only one "but": I do not like the title "Dashboard" as it is not telling me much about what I can do here and I think a lot of users do not know the meaning of the word. And in my opinion, when I upload or record a video I do manage my content in a way that it gets more/bigger. :) But if the majority is for "Dashboard" (or some other wording), I can live with it.

**Comment by LukasKalbertodt** [comment]
> Change wording for "Persönliche Seite"/"Your page" to "Meine Seite"/"My page".

+1 
Funny how I never noticed this obvious inconsistency in wording :D 

---

> Change icon for "Persönliche Seite"/"Your page" (Is this a flame?). See mockup.

Our icons should come from either ["Feather Icons"](https://feathericons.com/?query=user) or ["Hero Icons 1.x" (outline)](https://v1.heroicons.com/). In both, there is an icon named `user` that comes close to the one you suggested (but as outline, not solid icon). Is that what you had in mind?

However, I'm not sure if this standard, generic "user" icon is really a good choice for "my page". For one, we already use that on mobile (narrow screens) in the header:

![image](https://github.com/elan-ev/tobira/assets/7419664/a9b65242-16ee-4396-87dc-412b803e8682)

And again, this user icon is very generic and I'm not sure it sufficiently communicates "my public page". People might expect user settings from this (like profile image or changing password, both of which do not exist in Tobira, to be clear). 
As an alternative, what do you think of creating our own icon by using the `document` icon of Hero icons and then putting `user` into it? Quick mockup:

![image](https://github.com/elan-ev/tobira/assets/7419664/177de889-daa0-4eb5-8bc1-2ca09249cca0)

So yeah, with that information, what do you think about the icon choice?

---

> Don't show the navigation item on the left. This would be the most straight forward option to not confuse users. And users who are aware of the breadcrumb can still use this option to navigate back to the dashboard

I'm not sure if that would actually help not to confuse users. Having the navigation is something users likely expect. And not showing it while still having the main content aligned as in your screenshot would be a bit hacky. I don't think it's too bad to have a slightly different navigation than the big buttons there. But if it really bothers you, one could always add a navigation item "Record video" that just shows an almost empty page with "you can record blabla via Opencast Studio. Click here to open that". Would that be better in your opinion?

---

> Use the same order for the options (in the middle and to the right)

Good point.

---

> > Improve consistency: Momentarily we have "Verwalten" (to the right), "Dashboard" (as title of the page) and "Verwaltung" (as breadcrumb). My suggestion: Rename "Dashboard"/"Management Dashboard" to "Inhalte verwalten"/"Manage content".
>
> That's a "no" from me. You can also upload content, that's not "Manage content" (nor is recording a video). Make it "Dashboard".

> I do not like the title "Dashboard" as it is not telling me much about what I can do here and I think a lot of users do not know the meaning of the word.

I agree we should improve consistency and I also find just "dashboard" too generic and I don't think it tells the users much. But yes, "manage content" is also not ideal IMO.

As a comparison, YouTube uses "YouTube Studio" in user menu, which links to `studio.youtube.com`. Arriving there, you have a navigation on the left where the top item (the selected one) is "Dashboard". The heading for the page reads "Channel dashboard".

![image](https://github.com/elan-ev/tobira/assets/7419664/60de0132-3e46-49ab-9d49-74c3f2c4c0fd)

So they don't use the same wording for these three places. We can still try to unify it for Tobira, but I don't think it's toooo important? 

The term "studio" is obviously out for us. I do like the term "dashboard" for this page we are talking about: it is/should serve as a dashboard as it will show the most important information and available actions at a glance. Notably, the most important ones. Once Tobira gets more features, it might very well be that not everything a user can do is linked from the dashboard, but only from the navigation (like on YouTube). At least that's how I envisioned it in my head.

As one of my favorite uses of ChatGPT, I asked it for names (this is not a joke). Here are some of its suggestions:

- Dashboard
- Control Panel
- Management Hub
- User Console
- Creator Hub
- Command Center
- Video Manager

I do like the word "hub". "Management hub" would describe it quite well I think but "management" is a mouthful and also doesn't sound very hip and cool. "User Hub"? "Content Hub"? "Video Hub"? "Media Hub"? "My Hub"?

Any opinions or more suggestions?

---

> Invest some time in rewriting some explanations for the 4 options.

What's wrong with the current options? Like, it's fine, I'm not grumpy :D  but before trying to find new texts, we should be clear what the problem with the old texts are, as otherwise the search for new texts is pretty aimless.


> Produzieren Sie Videos, indem Sie Ihren Bildschirm, Ihre Webcam und ihr Mikrofonsignal aufnehmen

In the current version, all descriptions start with "Hier können/finden Sie" / "Here you can". This would change that and be inconsistent with your other suggestion. Also I'm not sure "Produzieren" is a better term than "Erstellen". I would assume "erstellen" is clearer to most people.

> Auf Ihren persönlichen Webseiten können Sie Videos, Text und andere Element kombinieren.

I wouldn't use "website", but stick to just "page". Website would imply a completely own ... domain. Your change from singular to plural is certainly worth considering. But here again, I would say "anordnen" is a more fitting term than "kombinieren". 

So again regarding all suggestions: what is it that we are even trying to improve here?

**Comment by LukasKalbertodt** [comment]
For your information, a few changes we discussed here have been implemented in #819. This should be available on `tobira.opencast.org` shortly. These were just the things that everyone here seemed to agree on: "your page" -> "my page", making the "manage pages?" a normal text below the tiles instead of a tile, and reordering the tiles to match the user menu. 

Our plan would be to release Tobira 2.0 like this. Further improvements discussed here should be fine to "only" include in 2.1. If you disagree, please let us know as 2.0 will be released Monday latest ^_^

**Comment by oas777** [comment]
Catching up after the 2.0 release:

- David: "Change **icon** for "Persönliche Seite"/"Your page"". I'm fine with the new icon Lukas suggested. If it survives [Lisa's review](https://github.com/elan-ev/tobira/issues/805).
- David: "Don't show the **navigation** item **on the left**". +1 from me. I see the arguments Lukas makes, but this is a page where the same navigation appears three times, that has to be a reason for an exception. Alternatively, we add this decision to https://github.com/elan-ev/tobira/issues/805.
- **Page title**: I'm open to "something something Hub". But it's definitively not better than "Dashboard", especially when you add another "empty" word like "management" (and it's longer than "Dashboard"). Coherence is the more important issue.
- Text explanation for the "four elements": Let's take this to https://github.com/elan-ev/tobira/issues/857.
- "Seiten verwalten?" This has got to go. 99% of users don't manage pages except for their own one. Can we take this to the the "My page" page https://tobira.opencast.org/@admin?
- Rearrange the four elements:
![image](https://github.com/elan-ev/tobira/assets/1752342/9268acdf-f9ee-429a-98c7-08d660fba1d5)

**Comment by dagraf** [comment]
>     * David: "Change **icon** for "Persönliche Seite"/"Your page"". I'm fine with the new icon Lukas suggested. If it survives [Lisa's review](https://github.com/elan-ev/tobira/issues/805).
I'm fine, too.
 
>     * David: "Don't show the **navigation** item **on the left**". +1 from me. I see the arguments Lukas makes, but this is a page where the same navigation appears three times, that has to be a reason for an exception. Alternatively, we add this decision to [Open design issues: Discussion with Lisa #805](https://github.com/elan-ev/tobira/issues/805).
I have no strong opinions here. I'm fine with either solutions (keep it as it is vs. not showing it at all vs. offering also "Video aufnehmen").

>     * **Page title**: I'm open to "something something Hub". But it's definitively not better than "Dashboard", especially when you add another "empty" word like "management" (and it's longer than "Dashboard"). Coherence is the more important issue.
Hub or Dashboard makes no difference to me. If all of you do not like "Inhalte verwalten" I would prefer "Dashboard".

>     * "Seiten verwalten?" This has got to go. 99% of users don't manage pages except for their own one. Can we take this to the the "My page" page https://tobira.opencast.org/@admin?
+1

**Comment by oas777** [comment]
Summary from Wednesday's meeting:

**Icon "My page"**
“document-text” oder “document-remove" von [hero icons](https://v1.heroicons.com/) mit einer/zwei Zeile Text und Play Icon (von Paella) 
![grafik](https://github.com/elan-ev/tobira/assets/1752342/9124951d-f135-4705-8a91-e3bb487f2286)

**Navigation**
Given it won't feature all links/features presented in other elements, it should "disappear" here - but only if the horizontal alignment of the page doesn't change as a result. Otherwise, we'll keep it with reduced links/features listed.

**Wording**
Coherence is key: Navigation, breadcrumb, tiles, and user menu should all have "Dashboard", maybe "Verwalten" in German. Given breadcrumb and page title are so close, can we get rid of the title? 
![grafik](https://github.com/elan-ev/tobira/assets/1752342/7a82f7df-361e-4ea1-8ed2-58a71d659c98)
If not, these two should not be coherent.

**Additional tiles**
Definitively "My series" and "Latest videos", maybe "Live events"

**Delete "Seiten verwalten" Text**


-
