### ISSUE TITLE
Add button tooltips are cut off on smaller screens

### ISSUE THREAD

**Issue by owi92** [elan-ev/tobira#850]
Happens at screen widths below ~510px. Tooltips don't work on mobile right now but this should get fixed regardless.
<img width="630" alt="Bildschirmfoto 2023-05-15 um 20 10 32" src="https://github.com/elan-ev/tobira/assets/94838646/4d4bcbb0-3ab7-4d01-8800-3763005307f7">

**Comment by owi92** [comment]
Apparently it's not that easy to make the tooltip text wrap in two lines or more. 
But there are two other options:
1. Position the tooltip at the bottom (it was this way before iirc, not my favorite)
2. Reword the tooltip to be more concise: 
    - english: "Insert a new block here" -> "Insert new block"
    - german: "Hier einen neuen block einfügen" -> "Neuen Block einfügen"

I think option 2 makes a lot of sense as it would also match the other tooltips on that page better (i.e. "remove block", "edit block" etc). The "here" part of the tooltip is heavily implied by the button's positioning anyway.
Let me know your thoughs.

**Comment by LukasKalbertodt** [comment]
So the "here" part of the label was deliberate to point the user to that fact. But mh, maybe it's implied enough? Or maybe users don't see the other "add" buttons, but only the first one? Not sure.

> Apparently it's not that easy to make the tooltip text wrap in two lines or more.

It's surely not easy to do that perfectly, but what if we just... do something a bit hacky? The `tooltip` prop of `WithTooltip` can be a react node. This seems to work?

```tsx
<WithTooltip
    tooltip={
        <div css={{ maxWidth: "35vw" }}>
            {t("manage.realm.content.add")}
        </div>
    }
    placement="right"
>
```

It's certainly not perfect because the tooltip "area" can be wider than required by its text, but I'd think it's alright? :shrug:

**Comment by owi92** [comment]
Yup that works. Didn't even consider the possibility. 
Regarding the wording: While I do think the "here" part (in relation to position, that's what I meant in my other comment) is implied enough and that tooltips should be as concise as possible, the point you made about only seeing the first button is fair. So let's stick with your suggestion.
