### ISSUE TITLE
Wording: DE/EN coherence

### ISSUE THREAD

**Issue by oas777** [elan-ev/tobira#857]
Can you extract the relevant "wording" so that we can take an overall look instead of discussing it here (Dashboard) and there (metadata/upload)?

**Comment by oas777** [comment]
Saving one discussion from https://github.com/elan-ev/tobira/issues/808:

-     Hier können Sie Videos von Ihrem Computer hochladen.
-     **Erstellen** Sie Videos, indem Sie Ihren Bildschirm, Ihre Webcam und ihr Mikrofonsignal aufnehmen
-     Hier finden Sie Ihre Videos und können diese verwalten und bearbeiten.
-     Auf Ihren persönlichen **Seiten** können Sie Videos, Text und andere Element kombinieren.

vs. 

-     Hier können Sie Videos von Ihrem Computer hochladen.
-     Hier können Sie Sie Videos **erstellen**, indem Sie Ihren Bildschirm, Ihre Webcam und ihr Mikrofonsignal aufnehmen
-     Hier finden Sie Ihre Videos und können diese verwalten und bearbeiten.
-     Hier können Sie auf Ihrer persönlichen **Seite** Videos, Text und andere Element kombinieren.

**Comment by owi92** [comment]
The translation files can be found here: 
https://github.com/elan-ev/tobira/tree/master/frontend/src/i18n/locales

**Comment by oas777** [comment]
Danke. Ich lege hier mal meine Notizen dazu ab für eine spätere Diskussion.
[Wording Tobira DE.docx](https://github.com/elan-ev/tobira/files/11518505/Wording.Tobira.DE.docx)

**Comment by oas777** [comment]
Ole, if I remember correctly, red parts of the text highlighted my suggestions for change. So I have to check whether these red passages are now in https://github.com/elan-ev/tobira/blob/master/frontend/src/i18n/locales/de.yaml, right? That's the latest wording/translation files?

**Comment by owi92** [comment]
The latest translation file including my recent changes is at https://github.com/elan-ev/tobira/blob/a51626b9403fe5e00f33505cff6828d482dad692/frontend/src/i18n/locales/de.yaml or, if you want to see these "in action" you can do so at https://pr987.tobira.opencast.org/ (though it's probably better to just look at the file instead, since some translations are sometimes hard to find in the deployment).

- I was asking about things like the below, which does not appear to be a suggestion (this and the other red things have been like that before).

<img width="549" alt="Bildschirmfoto 2023-11-10 um 10 38 55" src="https://github.com/elan-ev/tobira/assets/94838646/57b4000a-fbfd-4ae1-89b0-2af7a3ee4430">




- Suggestions you made look like in the next screenshot, and I have changed those in the link I gave you at the top.

<img width="544" alt="Bildschirmfoto 2023-11-10 um 10 43 45" src="https://github.com/elan-ev/tobira/assets/94838646/0d4f95ac-ee60-4f0f-a683-6f59ab28f32e">

**Comment by oas777** [comment]
- Die meisten (roten) Punkte hast du bereits umgesetzt, danke.
- Einige habe ich noch unter https://tinyurl.com/yquy3bj7 ergänzt bzw. entsprechend meiner Vorschläge korrigiert - kannst du diese Punkte nachvollziehen?
- "Noch keine Seiten..." und "Option auswählen..." fand ich wegen der Punkte so unbestimmt - weiss aber auch gar nicht, wo dieser Text zum Einsatz kommt. Hättest du mir das konkrete Beispiel bitte?
- Ausserdem gab es noch eine Grundsatzfrage nach "Episode" und "Serie", ob insbesondere Ersteres nicht durch "Video" ersetzt werden könnte. Was meinst du?

**Comment by oas777** [comment]
Uuups.

- You have already implemented most of the (red) points, thank you.
- I have added some at https://tinyurl.com/yquy3bj7 or corrected them according to my suggestions - can you see these points?
- I found "No pages yet..." and "Select an option..." so vague because of the points - but I don't even know where this text is used. Could you please give me the specific example?
- There was also a fundamental question about “episode” and “series”, whether the former in particular could not be replaced by “video”. What do you think?

**Comment by owi92** [comment]
> Unfortunately not. What you can do is commit and push your changes there, then I should be able to see them. I made a super short video where this is shown:
https://github.com/elan-ev/tobira/assets/94838646/27d4a354-d791-48fd-b451-cb520cc9da2e
I think that should work.

As follow up, I should probably mention that this is not what I would usually recommend. This is purely based on the assumption that you can still see your changes there. In that case, what I described above would be the easiest way for you to share your suggestions. Otherwise I would recommend that you make another word document, like you did before.

**Comment by oas777** [comment]
With respect to  "No pages yet..." and "Select an option...": I would delete the tree points, but I can live with you not doing so. But if  you don't, please make sure there isn't a blank/space before the dots like the one I think I see in your screenshot of "Noch keine Seiten ...".
And about the editing: I only did some very minor changes, so let's keep it at that. I don't think I will come across a similar task in the near future...

**Comment by LukasKalbertodt** [comment]
Actually :nerd_face:, [as per DIN 5008](https://www.sekretaria.de/bueroorganisation/korrespondenz/din-5008/auslassungspunkte/), in German one should use a space before "..." in most situation. I wasn't aware of this for a long time but learned a couple years ago. Also relevant: [this section of the Wikipedia article](https://de.wikipedia.org/wiki/Auslassungspunkte#Stilmittel) talking about the use as "Stilmittel" which is the case here I think.

That said, I also don't mind removing them :D I was accused multiple times already of using the Auslassungspunkte too much ...

**Comment by oas777** [comment]
Alt wie 'ne Kuh und lernt noch dazu ... with this in mind, you can handle them points anyway you like.
