### ISSUE TITLE
Why is the editor unavailable?

### ISSUE THREAD

**Issue by oas777** [elan-ev/tobira#865]
I did start a workflow a couple of hours ago, but that shouldn't be the result:

![image](https://github.com/elan-ev/tobira/assets/1752342/59024664-43a8-4a32-a6c7-113ce2eb33c5)

**Comment by LukasKalbertodt** [comment]
Sometimes workflow just end up in "pending" and never run :/ That's just an issue with out test deployment Opencast (the one used for `tobira.opencast.org`). Since it happens rarely, I haven't really looked into it yet. I just restarted that Opencast and now the workflows ran. Will close as it is resolved from my point of view. Assigning your for your approval. 

If this happens again in the future, just ping me so I can quickly restart Opencast. If this continues to happen regularly, I should maybe look into it.

**Comment by oas777** [comment]
Danke! Der Workflow wurde tatsächlich fortgesetzt bzw. beendet: https://tobira.opencast.org/v/MxjPITs7evh.
